#!/bin/sh
test "$#" -ne 1 \
&& ( echo "usage: bookmarks <browser> <urlprefix> <bookmarks.txt> <dmenuopts ...>" 1>&2
     exit 1 )
browser="$1"
urlprefix="$2"
bookmarkstxt="$3"
shift 3
bookmark=$(cat "$bookmarkstxt" | dmenu -p "$bookmarkstxt" "$@")
test "$?" -ne 0 && exit
"$browser" "$urlprefix""$bookmark" &
